name: Build,Analyze,scan

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build,Analyze,scan
    #runs-on: [self-hosted]
     runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis
          
     # - uses: sonarsource/sonarqube-scan-action@master
       # env:
        #  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you want (you can change this as needed)

      - name: Install dependencies (npm)
        run: npm install  # This installs the dependencies listed in package.json

      - name: Trivy file scan
        run: trivy fs . > trivyfs.txt

      - name: Docker build and run
        run: |
          docker build -t myntra .
          docker tag myntra prashant680844/myntra:latest
          docker log -u prashant680844 -p Yamini123@
          #docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push prashant680844/myntra:latest
        env:
          DOCKER_CLI: 1
  
      - name: Pull the Docker image
        run: docker pull prashant680844/myntra:latest

      - name: Trivy image scan
        run: trivy image prashant680844/myntra:latest

      - name: Run Docker container
        run: docker run -d --name myntra -p 3000:3000 prashant680844/myntra:latest
        
      - name: Deploy to container
        run: |
          docker stop myntra
          docker rm myntra 

      - name: Update kubeconfig
        run: aws eks --region ap-south-1 update-kubeconfig --name EKS_CLOUD

      - name: Deploy to kubernetes
        run: kubectl apply -f deployment.yaml  
    
      - name: Send a Slack Notification
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#prashant-githubaction'
        env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
